# -*- coding: utf-8 -*-
"""incremental_load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-_mM80kApc7x4XVUaNrhH9_xX_DB12c

Full load
"""

import requests
import json
import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("COINGECKO_API_KEY")
#API_KEY = 'CG-Pi8iNoVbVck4iGJiNu9sZFzE'
url = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"

params = {
    "vs_currency": "usd",
    "days": "7",
    "interval": "hourly"

}

headers = {
    "x-cg-demo-api-key": API_KEY
}

response = requests.get(url, params=params, headers=headers)

data = response.json()

os.makedirs("data/raw/incremental_load", exist_ok=True)

with open("data/raw/incremental_load/bitcoin_7_days_hourly.json", "w") as file:
    json.dump(data, file, indent=4)

print("Incremental Load file saved successfully!")